language: generic

sudo: required

services:
   - docker
   

before_install:
   - docker build -t abarry/travis-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true abarry/travis-cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"

Traviscicd-env.eba-uvpc2fwx.eu-central-1.elasticbeanstalk.com 

app: "travis-cicd"

env: "Traviscicd-env"
bucket_name: "elasticbeanstalk-eu-central-1-028103363534"
bucket_path: "Travis-cicd"
on:
  branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

