language: generic

sudo: required

services:
   - docker
   

before_install:
   - docker build -t abarry/travis-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true abarry/travis-cicd npm run test


